# Generated by Django 3.1 on 2020-09-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200906_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company', to='products.company'),
        ),
    ]
